name: Cleanup PR Resources

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@5fca0c5e51b4b0bd2cccfd52d517e5d1a9a575d8 # 1.4.1
