name: Cleanup PR Resources

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@2e3882b962944f14568afd6c3578a62c47616a60 # 1.5.1
