name: Cleanup PR Resources

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@9be49711ed44b2a7b65511bb4782a4e77d8f7184 # 1.3.28
