---
name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Full version including build number, e.g. 1.2.3.456'
        required: true
        type: string
      dryRun:
        description: 'Flag to enable the dry-run execution'
        required: false
        default: false
        type: boolean

env:
  PYTHONUNBUFFERED: 1

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@8974b5c27a786cdf7bba286a2fff5d12a2f7d78a # 7.2.0
    with:
      version: ${{ inputs.version }}
      publishToBinaries: true
      dryRun: ${{ inputs.dryRun }}
      slackChannel: C02E6L5C01H # squad-devex-private
