name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          version: 2026.6.1
      - uses: SonarSource/ci-github-actions/build-gradle@3c6565f5a65282d333ab60c8a0fa733c09e613d3 # 1.8.7
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          gradle-args: ":jacocoTestReport"
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@03e023516511b1c9da325ad104c2290e3b91688c # 1.1.0
        with:
          primary_project_key: "SonarSource_sonarqube-mcp-server"
          primary_platform: "SQC-EU"
          shadow1_project_key: "SonarSource_sonarqube-mcp-server"
          shadow1_platform: "Next"
          shadow2_project_key: "SonarSource_sonarqube-mcp-server"
          shadow2_platform: "SQC-US"
